version: '3'
services:
  psql-server:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: develop
    volumes:
      - ../src/main/resources/database:/docker-entrypoint-initdb.d
  mipams-crypto:
    image: crypto:0.0.1-SNAPSHOT
    ports:
      - 8080:8080
    depends_on: 
      - psql-server
  mipams-privsec:
    image: jumbf-privsec:0.0.1-SNAPSHOT
    ports:
      - 8081:8080
    depends_on: 
      - mipams-crypto