version: '3'
services:
  demo-server:
    image: mipams/jumbf-server:latest
    build:
      context: ../demo-server/
    ports:
      - 8081:8080
    environment:
      org_mipams_core_image_folder: "/app/assets"
      org_mipams_core_max_file_size_in_bytes: 52428800
      org_mipams_core: "INFO"
      spring_servlet_multipart_max-file-size: 128MB
      spring_servlet_multipart_max-request-size: 128MB
      spring_servlet_multipart_enabled: "true"
  demo-client:
    image: mipams/jumbf-ui:latest
    build:
      context: ../demo-client/
    volumes:
      - '../demo-client:/app'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - demo-server
    stdin_open: true